# Generated by Django 3.0.7 on 2020-06-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Staff'), (1, 'Admin'), (2, 'Church Member')], default=0),
        ),
    ]
